=== srinivaskakarala/Hendall_Workspace/Survey/ejb/target/classes/Survey.schema_v0_5a.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Generic JSON Schema for CMS Surveys",
  "description": "Generic JSON schema for CMS surveys",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "surveyID": {
      "description": "unique identifier allowing an answer JSON file to be linked to a particular survey/version JSON file",
      "type": "integer"
    },
    "stylesheet": {
      "description": "a url link to a CSS stylesheet which will be applied to html generated from the JSON data file",
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "version": {
      "type": "string"
    },
    "versionHistory": {
      "type": "string"
    },
    "creationDate": {
      "type": "string"
    },
    "lastModifiedDate": {
      "type": "string"
    },
    "author": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "instructions": {
      "type": "string"
    },
    "help": {
      "description": "Survey specific links for the 'Help' menu and stored are stored here",
      "type": "array",
      "items": {
        "helpSectionName": "string",
        "helpSectionLink": "array",
        "items": {
          "helpLinkName": "string",
          "helpLinkURL": "string"
        }
      }
    },
    "section": {
      "description": "Logical grouping of questions",
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "title": {
            "type": "string"
          },
          "question": {
            "type": "array",
            "items": {
              "type": "object",
              "additionalProperties": false,
              "properties": {
                "questionText": {
                  "description": "text for each question stored here",
                  "type": "string"
                },
                "fileUpload": {
                  "description": "flag indicating whether to a file upload button assocaited with a question",
                  "type": "boolean"
                },
                "htmlControl": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                      "controlID": {
                        "description": "unique identifier for a particular html control, matches column in db",
                        "type": "integer"
                      },
                      "controlType": {
                        "type": "string"
                      },
                      "placeholder": {
                        "type": "string"
                      },
                      "fieldSize":
                      {
                        "type": "integer"
                      },
                      "fieldMaxLength":
                      {
                        "type": "integer"
                      },
                      "controlText": {
                        "description": "text for each control stored here",
                        "type": "string"
                      },
                      "parentControlID": {
                        "description": "allows html controls to be linked for navigation/validation purposes",
                        "type": "integer"
                      },
                      "fieldRequired": {
                        "type": "boolean"
                      },
                      "fieldDefaultVisibility": {
                        "type": "boolean"
                      }
                    },
                    "required": [
                      "controlID", "controlType"
                    ]
                  }
                }
              },
              "required": [
                "questionText"
              ]
            }
          }
        }
      }
    }
  },
  "required": [
    "surveyID",
    "stylesheet"
  ]
}

=== srinivaskakarala/Hendall_Workspace/Survey/ejb/target/classes/Hospital_Infection_Control_Worksheet_v0_4a.json
{
  "surveyID": 100,
  "stylesheet": "http://urltostylesheethere.css",
  "title": "Hospital Infection Control Worksheet",
  "version": "v0.4a",
  "versionHistory": "v0.4a - initial alpha version",
  "creationDate": "11/19/2015",
  "lastModifiedDate": "11/19/2015",
  "author": "C.K. Holmes",
  "description": "Hospital Infection Control Worksheet for CMS Specialty Surveys Website",
  "instructions": "<p>Instructions:<br><br>The following is a list of items that must be assessed during the on-site survey, in order to determine compliance with the Infection Control Condition of Participation. Items are to be assessed by a combination of observation, interviews with hospital staff, patients and their family/support persons, review of medical records, and a review of any necessary infection control program documentation. During the survey, observations or concerns may prompt the surveyor to request and review specific hospital policies and procedures. Surveyors are expected to use their judgment and review only those documents necessary to investigate their concern(s) or to validate their observations.<br><br>The interviews should be performed with the most appropriate staff person(s) for the items of interest, as well as with patients, family members, and support persons.</p>",
  "section": [
    {
      "title": "Hospital Characteristics",
      "question": [
        {
          "questionText": "Name",
          "htmlControl": [
            {
              "controlID": 100,
              "controlType": "textbox",
              "fieldSize": 50,
              "fieldMaxLength": 255,
              "fieldRequired": true
            }
          ]
        },
        {
          "questionText": "1. Hospital Name",
          "htmlControl": [
            {
              "controlID": 200,
              "controlType": "select",
              "fieldRequired": true
            }
          ]
        },
        {
          "questionText": "2. CMS Certification Number",
          "htmlControl": [
            {
              "controlID": 300,
              "controlType": "number",
              "fieldMaxLength": 6,
              "fieldRequired": true
            }
          ]
        },
        {
          "questionText": "3. Date of site visit",
          "htmlControl": [
            {
              "controlID": 400,
              "controlText": "From",
              "controlType": "date",
              "fieldRequired": true
            },
            {
              "controlID": 500,
              "controlText": "To",
              "controlType": "date",
              "fieldRequired": true
            }
          ]
        }
      ]
    },
    {
      "title": "Section 1.A. Infection Prevention Program and Resources",
      "question": [
        {
          "questionText": "1.A.1 The hospital has designated one or more individual(s) as its Infection Control Officer(s).",
          "fileUpload": true,
          "htmlControl": [
            
            {
              "controlID": 600,
              "controlText": "Yes",
              "controlType": "radio",
              "fieldDefaultVisibility": true
            },
            {
              "controlID": 600,
              "controlText": "No",
              "controlType": "radio",
              "fieldDefaultVisibility": true
            },
            {
              "controlID": 700,
              "controlType": "textarea",
              "placeholder": "Please enter surveyor notes here...",
              "parentControlID": 600,
              "fieldDefaultVisibility": true
            },
           
            {
              "controlID": 610,
              "controlText": "Yes",
              "controlType": "radio",
              "fieldDefaultVisibility": false
            },
            {
              "controlID": 610,
              "controlText": "No",
              "controlType": "radio",
              "fieldDefaultVisibility": false
            },
            {
              "controlID": 710,
              "controlType": "textarea",
              "placeholder": "Please enter surveyor notes here...",
              "parentControlID": 610,
              "fieldDefaultVisibility": false
            },
           
            {
              "controlID": 620,
              "controlText": "Yes",
              "controlType": "radio",
              "fieldDefaultVisibility": false
            },
            {
              "controlID": 620,
              "controlText": "No",
              "controlType": "radio",
              "fieldDefaultVisibility": false
            },
            {
              "controlID": 720,
              "controlType": "textarea",
              "placeholder": "Please enter surveyor notes here...",
              "parentControlID": 620,
              "fieldDefaultVisibility": false
            },
          
            {
              "controlID": 630,
              "controlText": "Yes",
              "controlType": "radio",
              "fieldDefaultVisibility": false
            },
            {
              "controlID": 630,
              "controlText": "No",
              "controlType": "radio",
              "fieldDefaultVisibility": false
            },
            {
              "controlID": 730,
              "controlType": "textarea",
              "placeholder": "Please enter surveyor notes here...",
              "parentControlID": 630,
              "fieldDefaultVisibility": false 
            },
            
            {
              "controlID": 640,
              "controlText": "Yes",
              "controlType": "radio",
              "fieldDefaultVisibility": false
            },
            {
              "controlID": 640,
              "controlText": "No",
              "controlType": "radio",
              "fieldDefaultVisibility": false
            },
            {
              "controlID": 740,
              "controlType": "textarea",
              "placeholder": "Please enter surveyor notes here...",
              "parentControlID": 640,
              "fieldDefaultVisibility": false  
            }
           
          ]
        },
        {
          "questionText": "1.A.2 The hospital has evidence that demonstrates the Infection Control Officer(s) is qualified and maintain(s) qualifications through education, training, experience or certification related to infection control consistent with hospital policy.",
          "htmlControl": [
          
            {
              "controlID": 800,
              "controlText": "Yes",
              "controlType": "radio",
              "fieldDefaultVisibility": true
            },
            {
              "controlID": 800,
              "controlText": "No",
              "controlType": "radio",
              "fieldDefaultVisibility": true
            },
            {
              "controlID": 900,
              "controlType": "textarea",
              "placeholder": "Please enter surveyor notes here...",
              "parentControlID": 800,
              "fieldDefaultVisibility": true
            }
            
          ]
        },
        {
          "questionText": "1.A.3 The Infection Control Officer(s) can provide evidence that the hospital has developed general infection control policies and procedures that are based on nationally recognized guidelines and applicable state and federal law.",
          "htmlControl": [
           
            {
              "controlID": 1000,
              "controlText": "Yes",
              "controlType": "radio",
              "fieldDefaultVisibility": true
            },
            {
              "controlID": 1000,
              "controlText": "No",
              "controlType": "radio",
              "fieldDefaultVisibility": true
            },
            {
              "controlID": 1100,
              "controlType": "textarea",
              "placeholder": "Please enter surveyor notes here...",
              "parentControlID": 1000,
              "fieldDefaultVisibility": true
            },
            
            
            {
              "controlID": 1200,
              "controlText": "Yes",
              "controlType": "radio",
              "fieldDefaultVisibility": false
            },
            {
              "controlID": 1200,
              "controlText": "No",
              "controlType": "radio",
              "fieldDefaultVisibility": false
            },
            {
              "controlID": 1300,
              "controlType": "textarea",
              "placeholder": "Please enter surveyor notes here...",
              "parentControlID": 1000,
              "fieldDefaultVisibility": false
            }

          ]
        }
     
      ]
    } ,
     {
      "title": "Section 1.B. Hospital QAPI Systems Related to Infection Prevention",
      "question": [
        {
          "questionText": "1.B.1 The Infection Control Officer(s) can provide evidence that problems identified in the infection control program are addressed in the hospital QAPI program (i.e., development and implementation of corrective interventions, and ongoing evaluation of interventions implemented for both success and sustainability).",
          "htmlControl": [
         
            {
              "controlID": 1800,
              "controlText": "Yes",
              "controlType": "radio",
              "fieldDefaultVisibility": true
            },
            {
              "controlID": 1800,
              "controlText": "No",
              "controlType": "radio",
              "fieldDefaultVisibility": true
            },
            {
              "controlID": 1900,
              "controlType": "textarea",
              "placeholder": "Please enter surveyor notes here...",
              "parentControlID": 1800,
              "fieldDefaultVisibility": true
            } 
          ]
       },
       {
          "questionText": "1.A.3 Test questions",
          "htmlControl": [
           
            {
