=== srinivaskakarala/Hendall_Workspace/JsonSchemaToJavaPojo/src/main/resources/schema/Survey.schema_v0_3a.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Surveys JSON Schema",
  "description": "first attempt at creating a JSON schema for all survey questions",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "surveyID": {
      "description": "unique identifier allowing an answer JSON file to be linked to a particular survey/version JSON file",
      "type": "integer"
    },
    "title": {
      "type": "string"
    },
    "version": {
      "type": "string"
    },
    "versionHistory": {
      "type": "string"
    },
    "creationDate": {
      "type": "string"
    },
    "lastModifiedDate": {
      "type": "string"
    },
    "author": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "instructions": {
      "type": "string"
    },
    "page": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "title": {
            "type": "string"
          },
          "question": {
            "type": "array",
            "items": {
              "type": "object",
              "additionalProperties": false,
              "properties": {
                "questionID": {
                  "description": "unique identifier allowing an answer in a JSON file to be linked to a particular question (must be used in association with 'surveyID'",
                  "type": "integer"
                },
                "text": {
                  "type": "string"
                },
                "displayMediaIcon": {
                  "description": "flag indicating whether to display media icon allowing capture of additional survey evidence (photo/sound/video)",
                  "type": "boolean"
                },
                "htmlControl": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                      "controlID": {
                        "description": "unique identifier for a particular html control",
                        "type": "integer"
                      },
                      "controlType": {
                        "type": "string"
                      },
                      "placeholder": {
                        "type": "string"
                      },
                      "text": {
                        "type": "string"
                      },
                      "parentControlID": {
                        "description": "allows html controls to be linked for navigation/validation purposes",
                        "type": "integer"
                      }
                    },
                    "required": [
                      "controlID", "controlType"
                    ]
                  }
                }
              },
              "required": [
                "questionID",
                "text"
              ]
            }
          }
        }
      }
    }
  },
  "required": [
    "surveyID"
  ]
}

=== srinivaskakarala/Hendall_Workspace/Survey/web/src/main/webapp/resources/ASCInfectionControlSurveyorWorksheet_v0_3a.json
{
  "surveyID": 1,
  "title": "ASC Infection Control Surveyor Worksheet",
  "version": "v0.3a",
  "versionHistory": "version history info here!!!",
  "creationDate": "6/10/2015",
  "lastModifiedDate": "6/25/2015",
  "author": "author info here!!!",
  "description": "",
  "instructions": "Instructions: The following is a list of items that must be assessed during the on-site survey, in order to determine compliance with the infection control Condition for Coverage.  Items are to be assessed primarily by surveyor observation, with interviews used to provide additional confirming evidence of observations.  In some cases information gained from interviews may provide sufficient evidence to support a deficiency citation. The interviews and observations should be performed with the most appropriate staff person(s) for the items of interest (e.g., the staff person responsible for sterilization should answer the sterilization questions). A minimum of one surgical procedure must be observed during the site visit. The surveyor(s) must identify at least one patient and follow that case from registration to discharge to observe pertinent practices. For facilities that perform brief procedures, e.g., colonoscopies, it is preferable to follow at least two cases. When performing interviews and observations, any single instance of a breach in infection control would constitute a breach for that practice. Citation instructions are provided throughout this instrument, indicating the applicable regulatory provision to be cited on the Form CMS-2567 when deficient practices are observed.",
  "page": [
    {
      "title": "Page 1",
      "question": [
        {
          "questionID": 1,
          "text": "1. ASC Name",
          "displayMediaIcon": true,
          "htmlControl": [
            {
              "controlID": 1,
              "controlType": "textbox"
            }
          ]
        },
        {
          "questionID": 2,
          "text": "2. Address, State and Zip Code",
          "htmlControl": [
            {
              "controlID": 2,
              "controlType": "textbox",
              "placeholder": "Address"
            },
            {
              "controlID": 3,
              "controlType": "textbox",
              "placeholder": "City"
            },
            {
              "controlID": 4,
              "controlType": "select",
              "text": "State"
            },
            {
              "controlID": 5,
              "controlType": "textbox",
              "placeholder": "Zip"
            }
          ]
        },
        {
          "questionID": 3,
          "text": "3. 10-digit CMS Certification Number",
          "htmlControl": [
            {
              "controlID": 6,
              "controlType": "number"
            }
          ]
        },
        {
          "questionID": 4,
          "text": "4. What year did the ASC open for operation?",
          "htmlControl": [
            {
              "controlID": 7,
              "controlType": "number"
            }
          ]
        },
        {
          "questionID": 5,
          "text": "5. Please list date(s) of site visit:",
          "htmlControl": [
            {
              "controlID": 8,
              "controlType": "date"
            },
            {
              "controlID": 9,
              "controlType": "date"
            }
          ]
        },
        {
          "questionID": 6,
          "text": "6. What was the date of the most recent previous federal (CMS) survey:",
          "htmlControl": [
            {
              "controlID": 10,
              "controlType": "date"
            }
          ]
        },
        {
          "questionID": 7,
          "text": "7. Does the ASC participate in Medicare via accredited �deemed� status?",
          "htmlControl": [
            {
              "controlID": 11,
              "controlType": "radio",
              "text": "Yes"
            },
            {
              "controlID": 12,
              "controlType": "radio",
              "text": "No"
            }
          ]
        },
        {
          "questionID": 8,
          "text": "7a. If YES, by which CMS-recognized accreditation organization(s)?",
          "htmlControl": [
            {
              "controlID": 13,
              "controlType": "radio",
              "text": "Accreditation Association for Ambulatory Health Care (AAAHC)"
            },
            {
              "controlID": 14,
              "controlType": "radio",
              "text": "American Associate for Accred. of Ambulatory Surgery Facilities (AAAASF)"
            },
            {
              "controlID": 15,
              "controlType": "radio",
              "text": "American Osteopathic Association (AOA)"
            },
            {
              "controlID": 16,
              "controlType": "radio",
              "text": "The Joint Commission (TJC)"
            }
          ]
        },
        {
          "questionID": 9,
          "text": "7b. If YES, according to the ASC, what was the date of the most recent accreditation survey?",
          "htmlControl": [
            {
              "controlID": 17,
              "controlType": "date"
            }
          ]
        }
      ]
    },
    {
      "title": "Page 2",
      "question": [
        {
          "questionID": 10,
          "text": "8. What is the ownership of the facility? (SELECT only ONE bubble)",
          "htmlControl": [
            {
              "controlID": 18,
              "controlType": "radio",
              "text": "Physician-owned"
            },
            {
              "controlID": 19,
              "controlType": "radio",
              "text": "Hospital-owned"
            },
            {
              "controlID": 20,
              "controlType": "radio",
              "text": "National corporation (including joint ventures with physicians)"
            },
            {
              "controlID": 21,
              "controlType": "radio",
              "text": "Other (please print):"
            },
            {
              "controlID": 22,
              "controlType": "textarea",
              "parentControlID": 21
            }
          ]
        },
        {
          "questionID": 11,
          "text": "9. What is the primary procedure performed at the ASC (i.e., what procedure type reflects the majority of procedures performed at the ASC)? (Select only ONE bubble)",
          "htmlControl": [
            {
              "controlID": 23,
              "controlType": "radio",
              "text": "Dental"
            },
            {
              "controlID": 24,
              "controlType": "radio",
              "text": "Endoscopy"
            },
            {
              "controlID": 25,
              "controlType": "radio",
              "text": "Ear/Nose/Throat"
            },
            {
              "controlID": 26,
              "controlType": "radio",
              "text": "OB/Gyn"
            },
            {
              "controlID": 27,
              "controlType": "radio",
              "text": "Ophthalmologic"
            },
            {
              "controlID": 28,
              "controlType": "radio",
              "text": "Orthopedic"
            },
            {
              "controlID": 29,
              "controlType": "radio",
              "text": "Pain"
            },
            {
              "controlID": 30,
              "controlType": "radio",
              "text": "Plastic/reconstructive"
            },
            {
              "controlID": 31,
              "controlType": "radio",
              "text": "Podiatry"
            },
            {
              "controlID": 32,
              "controlType": "radio",
              "text": "Other (please specify):"
            },
            {
              "controlID": 33,
              "controlType": "textarea",
              "parentControlID": 32
            }
          ]
        },
        {
          "questionID": 12,
          "text": "10. What additional procedures are performed at the ASC? (Select all that apply) Do not include the procedure type indicated in question 9.",
          "htmlControl": [
            {
              "controlID": 34,
              "controlType": "checkbox",
              "text": "Dental"
            },
            {
              "controlID": 35,
              "controlType": "checkbox",
              "text": "Endoscopy"
            },
            {
              "controlID": 36,
              "controlType": "checkbox",
              "text": "Ear/Nose/Throat"
            },
            {
              "controlID": 37,
              "controlType": "checkbox",
              "text": "OB/Gyn"
            },
            {
              "controlID": 38,
              "controlType": "checkbox",
              "text": "Ophthalmologic"
            },
            {
              "controlID": 39,
              "controlType": "checkbox",
              "text": "Orthopedic"
            },
            {
              "controlID": 40,
              "controlType": "checkbox",
              "text": "Pain"
            },
            {
              "controlID": 41,
              "controlType": "checkbox",
              "text": "Plastic/reconstructive"
            },
            {
              "controlID": 42,
              "controlType": "checkbox",
              "text": "Podiatry"
            },
            {
              "controlID": 43,
              "controlType": "checkbox",
              "text": "Other (please specify):"
            },
            {
              "controlID": 44,
              "controlType": "textarea",
              "parentControlID": 43
            },
            {
              "controlID": 45,
              "controlType": "checkbox",
              "text": "N/A"
            }
          ]
        },
        {
          "questionID": 13,
